In [1]:
import pandas as pd
import numpy as np
import sklearn as sk
import datetime as dt

In [2]:
dataset1=pd.read_csv('https://raw.githubusercontent.com/chidaksh/CosmosocClub/master/Parsec2023/user1_data.csv',delimiter=',')

In [3]:
dataset2=pd.read_csv('https://raw.githubusercontent.com/chidaksh/CosmosocClub/master/Parsec2023/user2_data.csv',delimiter=',')

In [4]:
df=pd.concat([dataset1,dataset2],ignore_index=True)
df['ttime'] = pd.to_datetime(df['ttime'])
df['ttime'] = df['ttime'].apply(lambda x: x.timestamp())

In [5]:
x=df.iloc[:,0:8].values

In [6]:
y=df.iloc[:,8:12].values

In [43]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [44]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values = np.nan,strategy='median')
imputer.fit(x_train)
x_train = imputer.transform(x_train)
x_test = imputer.transform(x_test)
imputer.fit(y_train)
y_train = imputer.transform(y_train)
y_test = imputer.transform(y_test)

In [45]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [46]:
from sklearn.ensemble import RandomForestRegressor
regressor=RandomForestRegressor(n_estimators=20,random_state=0)

In [47]:
regressor.fit(x_train,y_train)
y_pred=regressor.predict(x_test)

In [49]:
df1=pd.DataFrame({'Actual Temp':y_test[:,0],'Predicted Temp':y_pred[:,0],'Actual Humidity':y_test[:,1],'Predicted Humidity':y_pred[:,1],'Actual Moisture':y_test[:,2],'Predicted Moisture':y_pred[:,2]})

In [50]:
from sklearn.metrics import confusion_matrix,accuracy_score
print('Training Accuracy=',regressor.score(x_train,y_train))
print('Test Accuracy=',regressor.score(x_test,y_test))

Training Accuracy= 0.9884109563598159
Test Accuracy= 0.9328023643915752

In [51]:
pm1_mean=df['pm1'].mean()
pm1_std = df['pm1'].std()
num_samples = 20
pm1_random = np.random.normal(loc=pm1_mean, scale=pm1_std, size=num_samples)

In [52]:
pm2_mean=df['pm2'].mean()
pm2_std = df['pm2'].std()
num_samples = 20
pm2_random = np.random.normal(loc=pm2_mean, scale=pm2_std, size=num_samples)

In [53]:
pm3_mean=df['pm3'].mean()
pm3_std = df['pm3'].std()
num_samples = 20
pm3_random = np.random.normal(loc=pm3_mean, scale=pm3_std, size=num_samples)

In [54]:
am_mean=df['am'].mean()
am_std = df['am'].std()
num_samples = 20
am_random = np.random.normal(loc=am_mean, scale=am_std, size=num_samples)

In [55]:
sm_mean=df['sm'].mean()
sm_std = df['sm'].std()
num_samples = 20
sm_random = np.random.normal(loc=sm_mean, scale=sm_std, size=num_samples)

In [56]:
st_mean=df['st'].mean()
st_std = df['st'].std()
num_samples = 20
st_random = np.random.normal(loc=st_mean, scale=st_std, size=num_samples)

In [57]:
lum_mean=df['lum'].mean()
lum_std = df['lum'].std()
num_samples = 20
lum_random = np.random.normal(loc=lum_mean, scale=lum_std, size=num_samples)

In [58]:
start_time = dt.datetime(2023, 3, 11, 0, 0, 0)
end_time = dt.datetime(2023, 3, 31, 23, 59, 59)
num_seconds = (end_time - start_time).total_seconds() + 1
df_input= pd.DataFrame({
    'ttime': pd.date_range(start=start_time, end=end_time, periods=20),'pm1':pm1_random,'pm2':pm2_random,'pm3':pm3_random,'am':am_random,'sm':sm_random,'st':st_random,'lum':lum_random})
df_input['ttime'] = pd.to_datetime(df_input['ttime'])
df_input['ttime'] = df_input['ttime'].apply(lambda x: x.timestamp())
df_input

,ttime,pm1,pm2,pm3,am,sm,st,lum
0,1.678493e+09,2.086588,1.101870,29.703556,2.709776,7232.584719,27.390360,2539.835240
1,1.678588e+09,1.115092,3.415430,101.577973,0.067071,343.414696,28.946135,10942.440889
2,1.678684e+09,-0.043625,2.714701,74.845806,0.029366,2237.401473,26.023159,-1682.690524
3,1.678779e+09,0.841551,1.484531,48.664837,-0.711657,3528.106922,26.060604,5706.609147
4,1.678875e+09,-0.545410,2.202659,102.709010,1.941700,2589.364131,27.717847,-1880.274406
5,1.678970e+09,1.754423,2.821501,25.769272,1.928858,4178.873088,27.610617,9007.490017
6,1.679066e+09,0.527657,3.647301,117.301636,3.961289,2248.590438,27.090262,5663.862388
7,1.679161e+09,0.080828,4.308789,34.279776,6.153392,3156.358389,26.812943,858.675858
8,1.679257e+09,3.598093,3.580040,97.632236,1.126091,7646.351057,27.070877,4628.461699
9,1.679352e+09,0.037893,5.579703,68.931847,0.817750,6948.581681,26.530234,1931.977166
10,1.679448e+09,0.835507,2.273503,55.133352,-2.891345,1340.512081,26.181227,5735.203510
11,1.679543e+09,-0.188635,6.216958,96.293330,3.721038,5711.486167,27.605586,-419.108426
12,1.679639e+09,0.648279,0.839963,99.878795,-0.665522,2589.483177,29.032324,96.758886
13,1.679734e+09,-0.662844,1.761445,87.362293,1.661983,5335.455613,27.350190,-1529.788101
14,1.679830e+09,3.612797,2.008704,46.981901,0.320669,5897.200129,27.234976,-1844.860978
15,1.679925e+09,3.117258,0.970308,100.393380,-2.354337,1098.934911,25.939837,-51.628815
16,1.680021e+09,0.584452,2.705841,76.413118,-0.357452,1835.979238,26.261245,697.184644
17,1.680116e+09,2.187289,2.550836,64.851158,0.027944,5158.617461,26.993775,-2494.277912
18,1.680212e+09,1.646594,0.935004,80.143327,1.981517,10425.908663,26.742777,4370.294380
19,1.680307e+09,1.693109,2.348343,46.122960,0.175147,2424.502690,23.020925,4813.745773

In [59]:
x_input=df_input.iloc[:,0:8].values
df_slice=df.iloc[39487:390507,8:12]
y_input=df_slice.values

In [60]:
regressor.fit(x_input,y_input)
y_pred = regressor.predict(x_input)

In [61]:
df3=pd.DataFrame({'Temp':y_pred[:,0],'Humidity':y_pred[:,1],'Moisture':y_pred[:,2]})
df3

       Temp  Humidity    Moisture
0   19.6300   39.1385  93390.3095
1   19.2135   40.8225  93388.4890
2   19.3740   41.0390  93373.8305
3   19.0905   41.8500  93378.0040
4   19.6010   39.6440  93382.6360
5   18.3815   42.9405  93383.4895
6   16.1660   50.2655  93369.5030
7   15.8460   50.6270  93369.4135
8   15.2795   52.1185  93377.5740
9   15.2640   52.3375  93382.9635
10  15.3620   53.0480  93417.4795
11  16.3125   51.7315  93439.8175
12  18.5360   46.3970  93464.5860
13  23.6415   37.3105  93520.7980
14  25.4605   34.0850  93543.1700
15  27.2625   31.3515  93556.6660
16  28.3130   28.8915  93566.9715
17  30.0590   24.8595  93565.6045
18  29.9640   25.9070  93560.2920
19  31.0055   23.7665  93553.1190